services:
  postgres:
    container_name: 'library-db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=librarydb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '6420:5432'