INSERT INTO books (title, author, genre, language, available, rating, publisher, published_date, page_count,
                   description)
VALUES ('The Shining', 'Stephen King', 'Horror', 'English', TRUE, 4.5, 'Penguin Random House', '1977-01-28', 659,
        'A chilling tale of a haunted hotel and its doomed caretaker.', 'https://example.com/covers/theshining.jpg'),
       ('Foundation', 'Isaac Asimov', 'Sci-Fi', 'English', TRUE, 4.7, 'HarperCollins', '1951-06-01', 255,
        'A science fiction epic about the rise and fall of civilizations.',
        'https://example.com/covers/foundation.jpg'),
       ('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'English', TRUE, 5.0, 'HarperCollins', '1937-09-21', 310,
        'The journey of Bilbo Baggins through Middle-earth.', 'https://example.com/covers/thehobbit.jpg'),
       ('Murder on the Orient Express', 'Agatha Christie', 'Detective', 'English', TRUE, 4.2, 'Simon & Schuster',
        '1934-01-01', 256, 'A famous detective, Hercule Poirot, solves a murder aboard a train.',
        'https://example.com/covers/murderonorientexpress.jpg'),
       ('It', 'Stephen King', 'Horror', 'English', FALSE, 4.8, 'Penguin Random House', '1986-09-15', 1138,
        'A group of children battle a shape-shifting entity in their town.', 'https://example.com/covers/it.jpg'),
       ('The Martian', 'Andy Weir', 'Sci-Fi', 'English', TRUE, 4.6, 'Macmillan', '2011-02-11', 369,
        'An astronaut struggles to survive on Mars after being left behind.',
        'https://example.com/covers/themartian.jpg'),
       ('The Catcher in the Rye', 'J.D. Salinger', 'Drama', 'English', TRUE, 3.8, 'Little, Brown and Company',
        '1951-07-16', 277, 'A rebellious teenager recounts his life in New York City.',
        'https://example.com/covers/catcherintherye.jpg'),
       ('The Da Vinci Code', 'Dan Brown', 'Detective', 'English', TRUE, 4.3, 'Doubleday', '2003-03-18', 689,
        'A professor uncovers a conspiracy involving the Catholic Church.',
        'https://example.com/covers/davincicode.jpg'),
       ('The Shining', 'Stephen King', 'Horror', 'Spanish', TRUE, 4.5, 'Penguin Random House', '1977-01-28', 659,
        'A chilling tale of a haunted hotel and its doomed caretaker.',
        'https://example.com/covers/theshiningspanish.jpg'),
       ('Neuromancer', 'William Gibson', 'Sci-Fi', 'English', TRUE, 4.6, 'Penguin Random House', '1984-07-01', 271,
        'A cyberpunk novel about hacking and artificial intelligence.', 'https://example.com/covers/neuromancer.jpg'),
       ('The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 'English', TRUE, 4.7, 'DAW Books', '2007-03-27', 662,
        'A young man recounts the story of his rise to fame.', 'https://example.com/covers/nameofwind.jpg'),
       ('The Murder of Roger Ackroyd', 'Agatha Christie', 'Detective', 'English', TRUE, 4.1, 'Collins Crime Club',
        '1926-06-01', 300, 'A famous detective novel with a shocking twist.',
        'https://example.com/covers/murderrogerackroyd.jpg'),
       ('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'Spanish', TRUE, 5.0, 'HarperCollins', '1937-09-21', 310,
        'Bilbo Baggins se embarca en un viaje por la Tierra Media.', 'https://example.com/covers/thehobbitspanish.jpg'),
       ('The Silent Patient', 'Alex Michaelides', 'Mystery', 'English', TRUE, 4.3, 'Celadon Books', '2019-02-05', 368,
        'A woman kills her husband and then stops speaking.', 'https://example.com/covers/silentpatient.jpg'),
       ('The Outsider', 'Stephen King', 'Horror', 'English', TRUE, 4.2, 'Scribner', '2018-05-22', 560,
        'A detective investigates a brutal murder with supernatural elements.',
        'https://example.com/covers/theoutsider.jpg'),
       ('Sapiens', 'Yuval Noah Harari', 'Non-Fiction', 'English', TRUE, 4.5, 'HarperCollins', '2014-09-04', 443,
        'A brief history of humankind.', 'https://example.com/covers/sapiens.jpg'),
       ('The Big Sleep', 'Raymond Chandler', 'Detective', 'English', TRUE, 4.4, 'Alfred A. Knopf', '1939-04-01', 231,
        'A detective novel involving corruption and murder.', 'https://example.com/covers/bigsleep.jpg'),
       ('1984', 'George Orwell', 'Dystopian', 'English', TRUE, 4.6, 'Secker & Warburg', '1949-06-08', 328,
        'A man challenges a totalitarian regime.', 'https://example.com/covers/1984.jpg'),
       ('The Great Gatsby', 'F. Scott Fitzgerald', 'Drama', 'English', TRUE, 4.1, 'Charles Scribners Sons',
        '1925-04-10', 218, 'A tale of wealth, love, and betrayal in the 1920s.',
        'https://example.com/covers/greatgatsby.jpg'),
       ('Dune', 'Frank Herbert', 'Sci-Fi', 'German', TRUE, 5.0, 'Penguin Random House', '1965-08-01', 412,
        'A saga of politics, religion, and ecology set on a desert planet.', 'https://example.com/covers/dune.jpg'),
       ('The Dark Tower', 'Stephen King', 'Fantasy', 'English', TRUE, 4.7, 'Penguin Random House', '1982-06-01', 800,
        'A quest to reach the Dark Tower and save the universe.', 'https://example.com/covers/darktower.jpg'),
       ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Mystery', 'English', TRUE, 4.3, 'Norstedts Förlag',
        '2005-09-01', 465, 'A journalist and hacker investigate a 40-year-old disappearance.',
        'https://example.com/covers/dragon_tattoo.jpg'),
       ('Harry Potter and the Sorcerers Stone', 'J.K. Rowling', 'Fantasy', 'English', TRUE, 5.0, 'Bloomsbury',
        '1997-06-26', 223, 'A young wizard begins his adventure at Hogwarts.',
        'https://example.com/covers/harrypotter1.jpg'),
       ('Cien años de soledad', 'Gabriel García Márquez', 'Fiction', 'Spanish', TRUE, 4.8, 'Editorial Sudamericana',
        '1967-06-05', 417, 'A multi-generational story set in the fictional town of Macondo.',
        'https://example.com/covers/cienanosdesoledad.jpg'),
       ('Le Petit Prince', 'Antoine de Saint-Exupéry', 'Fantasy', 'French', TRUE, 4.9, 'Reynal & Hitchcock',
        '1943-04-06', 96, 'A young prince travels across planets and learns lessons on love and life.',
        'https://example.com/covers/lepetitprince.jpg'),
       ('Der Steppenwolf', 'Hermann Hesse', 'Philosophical', 'German', TRUE, 4.4, 'S. Fischer Verlag', '1927-11-01',
        286, 'The internal journey of a man struggling with the conflicts within himself.',
        'https://example.com/covers/dersteppenwolf.jpg'),
       ('La sombra del viento', 'Carlos Ruiz Zafón', 'Mystery', 'Spanish', TRUE, 4.7, 'Planeta', '2001-04-01', 487,
        'A young man in post-World War II Barcelona uncovers a literary mystery.',
        'https://example.com/covers/lasombradelviento.jpg'),
       ('Die Verwandlung', 'Franz Kafka', 'Classic', 'German', TRUE, 4.6, 'Fischer Verlag', '1915-10-01', 55,
        'A man transforms into a giant insect, causing his family to become estranged from him.',
        'https://example.com/covers/dieverwandlung.jpg'),
       ('LÉtranger', 'Albert Camus', 'Philosophical', 'French', TRUE, 4.8, 'Gallimard', '1942-05-17', 123,
        'A man in Algiers is indifferent to the world around him and finds himself involved in a senseless murder.',
        'https://example.com/covers/letranger.jpg'),
       ('El alquimista', 'Paulo Coelho', 'Adventure', 'Spanish', TRUE, 4.6, 'HarperCollins', '1988-11-01', 208,
        'A shepherd travels to Egypt to find treasure, learning about life and destiny along the way.',
        'https://example.com/covers/elalquimista.jpg'),
       ('Mémoires dune jeune fille rangée', 'Simone de Beauvoir', 'Biography', 'French', TRUE, 4.5, 'Gallimard',
        '1958-03-01', 424, 'The memoir of the famous feminist philosopher, exploring her early years and growth.',
        'https://example.com/covers/memoiresdunefille.jpg'),
       ('Die unendliche Geschichte', 'Michael Ende', 'Fantasy', 'German', TRUE, 4.9, 'Thienemann Verlag', '1979-09-01',
        448, 'A boy discovers a magical world through a book that seems to be alive.',
        'https://example.com/covers/dieunendlichegeschichte.jpg'),
       ('El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Romance', 'Spanish', TRUE, 4.7,
        'Editorial Mondadori', '1985-11-03', 348,
        'A passionate love story set in the Caribbean during the early 20th century.',
        'https://example.com/covers/elamorenlostiempos.jpg'),
       ('Le Comte de Monte-Cristo', 'Alexandre Dumas', 'Adventure', 'French', TRUE, 4.9, 'Pegasus', '1844-08-28', 1243,
        'A young man seeks revenge after being betrayed and imprisoned by his closest friends.',
        'https://example.com/covers/lecomtede.jpg'),
       ('Der Prozess', 'Franz Kafka', 'Dystopian', 'German', TRUE, 4.5, 'Schocken Verlag', '1925-08-01', 299,
        'A man is put on trial for an unknown crime, trapped in a bureaucratic nightmare.',
        'https://example.com/covers/derprozess.jpg'),
       ('Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 'English', TRUE, 4.4, 'Ballantine Books', '1953-10-19', 158,
        'In a future society where books are banned, a fireman starts questioning the regime.',
        'https://example.com/covers/fahrenheit451.jpg'),
       ('La Casa de los Espíritus', 'Isabel Allende', 'Historical Fiction', 'Spanish', TRUE, 4.6, 'Sudamericana',
        '1982-01-01', 498, 'A family saga spanning generations, incorporating magical realism and Chilean history.',
        'https://example.com/covers/lacasadelosespiritus.jpg'),
       ('Les Misérables', 'Victor Hugo', 'Historical Fiction', 'French', TRUE, 5.0, 'A. Lacroix, Verboeckhoven & Cie',
        '1862-01-01', 1465, 'A story of love, redemption, and the struggle for justice in post-revolutionary France.',
        'https://example.com/covers/lesmiserables.jpg'),
       ('Der Herr der Ringe: Die Gefährten', 'J.R.R. Tolkien', 'Fantasy', 'German', TRUE, 5.0, 'Klett-Cotta',
        '1954-07-29', 423, 'The first volume of Tolkiens epic fantasy saga, the story of the fellowships quest.',
        'https://example.com/covers/derherrderinge.jpg'),
       ('Moby-Dick', 'Herman Melville', 'Adventure', 'English', TRUE, 4.7, 'Harper & Brothers', '1851-10-18', 635,
        'A captains obsessive quest for the elusive white whale that leads to his doom.',
        'https://example.com/covers/mobydick.jpg'),
       ('Cien años de soledad', 'Gabriel García Márquez', 'Magical Realism', 'Spanish', TRUE, 4.9,
        'Editorial Sudamericana', '1967-06-05', 417,
        'A multi-generational saga filled with the magic and history of Colombia.',
        'https://example.com/covers/cienanosdesoledad2.jpg');